### PR TITLE
Upgrade to `infection/infection` 0.10

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by Ocramius** [comment]
I want 0 mutations overall

**Comment by lcobucci** [comment]
@Ocramius so it should be something like `vendor/bin/infection --min-msi=100 --min-covered-msi=100` https://infection.github.io/guide/using-with-ci.html

**Comment by Ocramius** [comment]
Aren't those the defaults?

**Comment by lcobucci** [comment]
@Ocramius nope, if you don't set them the exit code is always `0` regardless of the MSI or Covered MSI.

**Comment by Ocramius** [comment]
I'd ideally have a non-zero exit code at any mutation - coverage should
probably be checked independently, no?

**Comment by lcobucci** [comment]
> I'd ideally have a non-zero exit code at any mutation

AFAIK infection's developers decided to leave that decision up to the users, considering that there's always a chance of having false-positives.

> coverage should probably be checked independently, no?

It depends on the intention... Since MSI is the ratio between defeated mutants and total mutants where as Covered MSI is the ratio between defeated mutants and mutants covered by tests, some people might want to track only one, the other, or both.
The idea is that tracking MSI helps you to write MORE tests while covered MSI helps you to write BETTER tests.

I like to track both on my projects, but I had dealt with projects that were not thoroughly tested... leading to an initial setup like `--min-msi=X` (where X is the current MSI) `--min-covered-msi=100` to ensure that new changes won't drop the MSI and that existing (and new) tests are good.

**Comment by Ocramius** [comment]
Applied minimum thresholds as suggested by El Cobucci

**Pull request merged**
