### PR TITLE
Document usage in local develoment environment where HTTPS is not available (plain HTTP only)

### PR DESCRIPTION
**Pull request by mnapoli**
I struggled so much to make this work locally on `http://localhost:8000/`, here is an attempt at documenting it.

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
@mnapoli given that `example/` does provide SSL-less setup, perhaps endorsing local usage of SSL via mkcert?

Just throwing it out there: the reason why I say this, is that I regularly get poked at for anything that may seem "less secure" from crypto people that didn't read the docs, so I'm hesitant in adding docs on how to cut corners.

Alternatively, adding a large disclaimer to the newly added docs.

**Comment by Ocramius** [comment]
Failures unrelated to patch.

BTW, did you see the `examples/` dir? https://github.com/psr7-sessions/storageless/blob/20a60d5ef18ca4d895931f79b09eba17463b9ba5/examples/index.php#L48

**Comment by mnapoli** [comment]
> I regularly get poked at for anything that may seem "less secure" from crypto people that didn't read the docs, so I'm hesitant in adding docs on how to cut corners.

Yep, I definitely understand that.

> perhaps endorsing local usage of SSL via mkcert?

If I understand correctly that means `php -S ...` wouldn't work anymore? Sounds too bad (IMO), that's why I'm trying to find a solution for the simplest setup.

> BTW, did you see the examples/ dir? 

I did not find this through the docs. Maybe it could be made more visible (e.g. a visible link in the docs), but I don't find it perfect, it works but it doesn't explain why. E.g. it overrides the cookie name, which is important to make this work locally, but it's not explained so it's easy to dismiss this change and waste hours with a session that doesn't work.

> Alternatively, adding a large disclaimer to the newly added docs.

If you're OK with that, I'm fine adding a disclaimer, e.g.

```
**The setup described below is completely insecure. It should only be used for local development.**
```

Would that work?

**Comment by Ocramius** [comment]
> I did not find this through the docs. Maybe it could be made more visible (e.g. a visible link in the docs),

Fair enough: I generally look at examples before docs, so I may be too biased there :) 



 > > Alternatively, adding a large disclaimer to the newly added docs.
 > If you're OK with that, I'm fine adding a disclaimer, e.g.
 > ```md
 > **The setup described below is completely insecure. It should only be used for local development.**
 > ```
 > Would that work?

Yes, works.

**Comment by mnapoli** [comment]
Thanks, that's done!

**Comment by Ocramius** [comment]
Thanks @mnapoli!

**Pull request merged**
